# Generated by Django 4.2.3 on 2023-07-25 21:17

import core.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestOTP',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('Phone', 'Phone'), ('E-mail', 'Email')], default='Phone', max_length=10)),
                ('reciver', models.CharField(max_length=50)),
                ('password', models.CharField(default=core.models.random_pass, max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
